#!/bin/bash
docker pull durosoft/crystal-alpine:$1
docker run durosoft/crystal-alpine:$1 crystal --version
docker run --rm -it -v $PWD:/app -w /app durosoft/crystal-alpine:$1 crystal build test.cr -o output --release --static --no-debug
