#!/bin/bash
docker pull durosoft/crystal-alpine:0.26.0
docker run durosoft/crystal-alpine:0.26.0 crystal --version
docker run --rm -it -v $PWD:/app -w /app durosoft/crystal-alpine:0.26.0 crystal build test.cr -o output --release --static --no-debug
